export const surpriseMePrompts = [
  "A futuristic cityscape at sunset.",
  "An enchanted forest filled with bioluminescent plants.",
  "A steampunk-inspired airship soaring through the clouds.",
  "A whimsical underwater world with talking sea creatures.",
  "A cyberpunk street with neon lights and holographic billboards.",
  "An alien marketplace bustling with unique extraterrestrial goods.",
  "A time-traveling adventurer exploring ancient ruins.",
  "A floating island inhabited by mythical creatures.",
  "A magical library filled with enchanted books and scrolls.",
  "A post-apocalyptic wasteland with ruins of a once-great civilization.",
  "A dreamlike garden of oversized flowers and talking animals.",
  "A parallel universe where gravity works differently.",
  "A cityscape where buildings are made of living trees and plants.",
  "An abandoned spaceship drifting through the cosmos.",
  "A surreal landscape with floating islands and waterfalls in the sky.",
  "A desert oasis with a hidden underground civilization.",
  "A haunted mansion with ghostly apparitions.",
  "A high-tech space station orbiting a distant planet.",
  "A world where animals have evolved to have human-like abilities.",
  "A parallel dimension where mythical creatures roam freely.",
  "A hidden underground city with advanced technology.",
  "A secret garden with glowing flowers that emit music.",
  "A robotic jungle with mechanical animals and plants.",
  "A parallel universe with mirrored realities.",
  "An ancient temple guarded by mythical beasts.",
  "A city engulfed in a perpetual lightning storm.",
  "A deep-sea exploration with bioluminescent marine life.",
  "A cityscape with floating islands connected by bridges.",
  "A world where technology and nature coexist harmoniously.",
  "A vast crystalline cave filled with shimmering gems.",
  "A rainforest with bioluminescent flora and fauna.",
  "A futuristic amusement park with holographic rides.",
  "A realm of floating bubbles containing entire landscapes.",
  "A space colony on a distant exoplanet.",
  "A time-traveling adventure through different historical eras.",
  "A surreal circus with acrobatic mythical creatures.",
  "A city where animals and humans live together as equals.",
  "A world with floating islands made of candy and desserts.",
  "An ancient library guarded by mythical creatures.",
  "A city engulfed in an eternal sunset.",
  "A whimsical candy factory operated by robots.",
  "A virtual reality wonderland with endless possibilities.",
  "A land of giants with colossal plants and animals.",
  "A hidden cave filled with glowing crystals and gemstones.",
  "A world where dreams come to life as living entities.",
  "An undersea kingdom with mermaids and underwater castles.",
  "A metropolis powered by renewable energy sources.",
  "A world where mythical creatures are modern-day pets.",
  "An enchanted floating island with ancient ruins.",
  "A secret garden where time flows differently.",
];
